### ISSUE TITLE
作者能支持lombok的@RequiredArgsConstructor注解吗？

### ISSUE THREAD

**Issue by Alickx** [lly-ke/ImportBeanField#1]
因为使用这个注解的注入方式是使用
```java
private final RedissonClient redissonClient;
```
这样子的

**Comment by lly-ke** [comment]
已经支持了, 需要更新到2022.12.28版本 

在候选搜索框选中对应的bean, 按`alt+enter`打开高级设置然后选择Lombok构造函数注入方式
下次使用直接选中bean回车就行了(会使用之前配置) 就不用打开高级设置了

**Comment by Alickx** [comment]
> 已经支持了, 需要更新到2022.12.28版本
> 
> 在候选搜索框选中对应的bean, 按`alt+enter`打开高级设置然后选择Lombok构造函数注入方式 下次使用直接选中bean回车就行了(会使用之前配置) 就不用打开高级设置了

谢谢作者，挺好用的
