### ISSUE TITLE
没有对@MapperScan注解的支持

### ISSUE THREAD

**Issue by Stiles-Wangs** [lly-ke/ImportBeanField#19]
### 你现在所遇到的问题
启动项配置了@MapperSacn("XXXXX"),我可以不用去一个个加@Mapper了。但是很明显它不支持。搜索不到bean对象。

**Comment by lly-ke** [comment]
所有搜不到的bean, 可以按两次快捷键开启按类名称搜索注入(Mac: `command + shift + i` Windows: `ctrl + shift + o`) 


<img width="802" alt="image" src="https://github.com/lly-ke/ImportBeanField/assets/28623614/1f86ca74-7151-475c-84b4-c0e2cf469b80">

感谢你的反馈, 有空会优化这个问题

**Comment by Stiles-Wangs** [comment]
了解了。希望你可以优化一下。目前来看使用@MapperScan是个很常用的开发方式。
