### ISSUE TITLE
在idea最新版本2022.3.1中查找不到bean

### ISSUE THREAD

**Issue by Alickx** [lly-ke/ImportBeanField#2]
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
无法查找bean

### 重现步骤(如果有就写完整)
查找bean无法查找，但是查找包含Java类是正常的

### 报错信息(最好带上完整截图)
![image](https://user-images.githubusercontent.com/55425385/210515884-64be4b7f-beb4-4098-b220-d00beb6ce786.png)

**Comment by lly-ke** [comment]
1. 请问这个 `bean` (PostManageService类)是用什么方式丢到 spring 容器的,  `Service`注解吗?
2. 是所有bean无法查找还是只有部分 (没有勾选`查找包含Java类`)
3. 方便贴一下`PostManageService`类定义部分代码的截图吗

**Comment by Alickx** [comment]
> 1. 请问这个 `bean` (PostManageService类)是用什么方式丢到 spring 容器的,  `Service`注解吗?
> 2. 是所有bean无法查找还是只有部分 (没有勾选`查找包含Java类`)
> 3. 方便贴一下`PostManageService`类定义部分代码的截图吗

1. 和 3.  对的，是`@Service`注解
![image](https://user-images.githubusercontent.com/55425385/210551813-884ca7f2-a777-423e-9ea6-d9ded0ec50c2.png)
2. 是所有bean无法查找

**Comment by lly-ke** [comment]
离线安装包下载
链接: https://pan.baidu.com/s/10cwt1_qduKwFpE5_6dMGYA 提取码: crst

用最新的`ImportBeanField-2023.1.4.zip`安装试试

我的idea也是2022.3.1的一直是正常的, 很奇怪

![image](https://user-images.githubusercontent.com/28623614/210575729-db7f8481-973e-4825-a9ff-0bb1fab91c70.png)

**Comment by Alickx** [comment]
> 

我发现在其他项目中，插件是使用正常的，但是在我的项目中却无法查找bean，我的项目Springboot版本为2.7.3，Java版本为17，会不会是这个Springboot版本的原因？

**Comment by lly-ke** [comment]
那应该是idea没有识别出这是个spring类型的项目, 需要按下面方式开启应该就可以了

`File -> Proiect Structure -> Modules -> 右键项目 -> Add -> Spring`

![image](https://user-images.githubusercontent.com/28623614/210587007-02f5c081-2abf-4aab-a0ba-a4ad5cc9d5c3.png)

**Comment by Alickx** [comment]
> 那应该是idea没有识别出这是个spring类型的项目, 需要按下面方式开启应该就可以了
> 
> `File -> Proiect Structure -> Modules -> 右键项目 -> Add -> Spring`
> 
> ![image](https://user-images.githubusercontent.com/28623614/210587007-02f5c081-2abf-4aab-a0ba-a4ad5cc9d5c3.png)

ok，按照方法已经可以正常使用了，非常感谢~
